"""empty message

Revision ID: 1248fe49b523
Revises: 74aebe5e2647
Create Date: 2019-10-26 18:38:12.026919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1248fe49b523'
down_revision = '74aebe5e2647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paths', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('paths', sa.Column('lng', sa.Float(), nullable=False))
    op.add_column('paths', sa.Column('zoom', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paths', 'zoom')
    op.drop_column('paths', 'lng')
    op.drop_column('paths', 'lat')
    # ### end Alembic commands ###
