"""empty message

Revision ID: 74aebe5e2647
Revises: 
Create Date: 2019-10-26 18:29:18.351360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74aebe5e2647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('svg', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paths')
    # ### end Alembic commands ###
